### ISSUE TITLE
feature_extractors/omnivore/configs/PERCEPTION_TEST/OMNIVORE_feature.yaml

### ISSUE THREAD

**Issue by rixejzvdl649** [JacobChalk/TIM#11]
```python
MODEL:
  NUM_CLASSES: [97, 300]
  ARCH: omnivore_swinB
  MODEL_NAME: Omnivore
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
```

**Comment by rixejzvdl649** [comment]
NUM_CLASSES: [97, 300]

**Comment by rixejzvdl649** [comment]
feature_extractors/auditory_slowfast/configs/PERCEPTION/SLOWFAST_R50.yaml

```
MODEL:
  NUM_CLASSES: [97, 300]
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
```
